CREATE DATABASE shipt_challenge_db;

\c shipt_challenge_db;

CREATE TABLE products (
  product_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product VARCHAR(100) not null UNIQUE,
  unit_price DECIMAL not null
);

CREATE TABLE categories (
  category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category VARCHAR(100) not null UNIQUE
);

CREATE TABLE products_categories (
  pc_product_id INTEGER REFERENCES products(product_id),
  pc_category_id INTEGER REFERENCES categories(category_id),
  CONSTRAINT products_categories_pkey PRIMARY KEY(pc_product_id, pc_category_id)
);

CREATE TABLE customers (
  customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(100) not null,
  last_name VARCHAR(100) not null,
  email VARCHAR(100) not null UNIQUE
);

CREATE TABLE orders (
  order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status VARCHAR(100) DEFAULT 'WAITING',
  orders_customer_id INTEGER REFERENCES customers(customer_id),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  CHECK (status = 'WAITING' OR status = 'ON ITS WAY' OR status = 'DELIVERED')
);

CREATE TABLE orders_products (
  op_order_id INTEGER REFERENCES customers(customer_id),
  op_product_id INTEGER REFERENCES products(product_id),
  number_purchased INTEGER not null,
  CONSTRAINT orders_products_pkey PRIMARY KEY (op_order_id, op_product_id)
);
